= Esquema de descripción Lily
:toc:

Para poder trabajar con diversas arquitecturas, Lily necesita conocerlas a
detalle, lo que hacemos a través de archivos de descripción escritos en tablas
de Lua. Aquí se describe la estructura que debe tener dicha tabla de Lua para
ser reconocidas por el hipervisor.

== ``string`` __id__
Contiene un identificador para el procesador.

== ``table`` __registros__
La tabla registros contiene todos los registros utilizados por el
microprocesador. Es una tabla asociativa: cada índice corresponderá al nombre de
un registro reconocido, y contendrá una tabla que tendrá especificadas las
siguientes propiedades:

 ``tamano``:: Entero, tamaño en bits del registro.
 ``desplazamiento``:: Entero, ubicación del registro en la matriz de bits. Se ha
 de notar que varios registros pueden solaparse, y eso se controla con esta
 propiedad.

== ``table`` __operandos__
La tabla operandos contiene funciones para reconocer y obtener valores por cada
tipo de operando que un mnemónico pueda requerir. Es una tabla asociativa, cada
índice corresponde a un identificador para el tipo a definir, mientras que el
valor asociado será una función que acepte un solo parámetro: una cadena que
contiene al resto de la línea que aún no ha sido procesada que contiene los
argumentos tal cual se encuentran en el código fuente, finalizando con un
caracter de salto de línea. Esta función deberá devolver una tupla de dos
valores: el valor del parámetro reconocido (o `nil` si no hubo coincidencia con
esa función), y la cadena desde la cual se seguirán extrayendo parámetros.

Si un valor podría coincidir con más de un tipo, es importante notar que se
devolverá el primer tipo que haga coincidencia. Dado que éstas se procesan según
el orden en el que fueron agregadas en el código Lua, recomendamos incluir antes
las definiciones más específicas, y después, las más generales.

== ``table`` __ensamble__
La tabla ensamble contiene todos los mnemónicos del conjunto de
instrucciones. Es una tabla asociativa, cada índice corresponde a un mnemónico
reconocido, y el tipo del valor asociado a cada clave puede variar, dependiendo
de su función, pero normalmente, será una tabla que contendrá varias duplas,
representando cada una un conjunto de parámetros diferente. El primer elemento
de esta dupla será una tupla de cadenas, donde cada cadena será un marcador de
tipo (detallado en su sección), el segundo, un elemento de cualquiera de los
siguientes tipos:

 ``function``:: una función que recibirá los parámetros y devolverá una lista de
  enteros, representando la conversión a bytes.
 ``List<int>``:: su equivalencia en código máquina.
 ``Tuple<char*, function>``:: la cadena representa el nombre de otro mnemónico,
de modo que se debe usar el valor definido para esta combinación de parámetros
en dicho mnemónico. Después, se pasará la lista de bytes devuelta a la función
para aplicar alguna transformación.

Además, si un mnemónico no admite parámetros, pueden usarse como valor
cualquiera de los tres tipos descritos directamente, en vez de especificar una
opción con una lista de parámetros vacía.

== ``table`` __opcodes__

== ``table`` __desensamble__
