#!/bin/sh

# Copyright (C) 2026 Giovanni Alfredo Garciliano Diaz
#
# This file is part of Lily.
#
# Lily is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Lily is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Lily. If not, see <https://www.gnu.org/licenses/>.

base_dir="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$base_dir" ]; then
    echo "Debes estar dentro del repositorio para activar este entorno"
    return 1
fi

deactivate(){
    if [ -n "${LILY_OLD_PATH:-}" ]; then
        export PATH="$LILY_OLD_PATH"
        unset LILY_OLD_PATH
    fi
    if [ -n "${LILY_OLD_PS1:-}" ]; then
        export PS1="$LILY_OLD_PS1"
        unset LILY_OLD_PS1
    fi
    if [ -n "${LILY_GIT_REPO:-}" ]; then
        unset LILY_GIT_REPO
    fi
    hash -r 2>/dev/null
    unset deactivate
}

export LILY_OLD_PATH="$PATH"
export PATH="$base_dir/misc/scripts:$PATH"
export LILY_OLD_PS1="$PS1"
export PS1="(lily) $PS1"
export LILY_GIT_REPO="$base_dir"
hash -r 2>/dev/null
