#!/bin/sh

# Copyright (C) 2026 Giovanni Alfredo Garciliano Diaz
#
# This file is part of Lily.
#
# Lily is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Lily is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Lily. If not, see <https://www.gnu.org/licenses/>.

if [ ${#} -lt 1 ]; then return 2; fi
base_dir="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$base_dir" ]; then
    if [ -z "${LILY_GIT_REPO:-}" ]; then return 3; fi
    base_dir="$LILY_GIT_REPO"
fi
ret_val=0
for c in "$@"; do
    val=$(awk "BEGIN { FS=\",[[:blank:]]*/\\*\\*<[[:blank:]]*\"; COD=0; CODF=1; } /COD_/{if (\"$c\"==COD) { gsub(\"^[[:blank:]]*\", \"\", \$1); gsub(\"[[:blank:]]*\\*/\",\"\", \$2); print \"\\x1b[1m\"\$1\":\\x1b[0m \"\$2; CODF=0; } COD++;} END { exit CODF; }"< "$base_dir/src/common/estado.h")
    if [ "$?" -eq 1 ]; then ret_val=1; fi
    if [ -n "$val" ]; then
        if [ ${#} -gt 1 ]; then printf "\e[2m%s:\e[0m " "$c"; fi
        echo "$val"
    fi
done
return $ret_val;
