name: Generación de artefactos
run-name: Generación de artefactos para ${{github.sha}}
on: [ "push" ]
jobs:
  tarball:
    runs-on: ubuntu-slim
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Generar
        run: |
          make dist;
          echo "NOMBRE_DIST=$(find dist -regex .\*tar.gz)" >> $GITHUB_ENV
      - name: subir
        uses: actions/upload-artifact@v7
        with:
          name: tarball
          path: ${{env.NOMBRE_DIST}}
          if-no-files-found: error
          overwrite: true
          compression-level: 0
